version: '3.8'

services:
  sensor-api:
    build: ./sensor-api
    ports:
      - "5000:5000"
    env_file:
      - .env  # Load environment variables
    depends_on:
      - basic-versioning

  basic-versioning:
    build: ./basic-versioning
    command: ["python", "app.py"]
