version: '3.8'

services:
  sensor_api:
    build: ./sensor_api
    ports:
      - "5000:5000"
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    depends_on:
      - basic-versioning

  basic-versioning:
    build: ./basic-versioning
    command: ["python", "app.py"]
