name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code for Both Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Linting Tools
        run: pip install flake8

      - name: Lint basic-versioning
        run: flake8 basic-versioning/

      - name: Lint sensor-api
        run: flake8 sensor-api/

  test_versioning:
    name: Run Unit Tests for Versioning API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r basic-versioning/requirements.txt
          pip install pytest

      - name: Run Tests
        run: pytest basic-versioning/test_version.py

  test_sensor:
    name: Run Unit Tests for Sensor API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r sensor-api/requirements.txt
          pip install pytest

      - name: Run Tests
        run: pytest sensor-api/test_sensor.py

  build_versioning:
    name: Build and Push Versioning API Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t yourdockerhubusername/versioning-api:latest -f basic-versioning/Dockerfile .
          docker push yourdockerhubusername/versioning-api:latest

  build_sensor:
    name: Build and Push Sensor API Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t yourdockerhubusername/sensor-api:latest -f sensor-api/Dockerfile .
          docker push yourdockerhubusername/sensor-api:latest
